name: "🐛 Bug Report"
description: "Report a bug in the application"
title: "[BUG]: "
labels: ["bug"]
projects: "StellarTeams/4"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Briefly describe the bug, expected behavior, and actual behavior."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide steps to reproduce the bug."
    validations:
      required: false