name: "🔧 Chore"
description: "Miscellaneous or non-functional task"
title: "[Chore]: "
labels: ["enhancement"]
projects: "StellarTeams/4"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the task or maintenance work to be done."
    validations:
      required: true