name: "🎨 Code Style Change"
description: "Modify code style or formatting"
title: "[Style]: "
labels: ["enhancement"]
projects: "StellarTeams/4"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the code style or formatting changes."
    validations:
      required: true