name: "♻️ Refactor"
description: "Propose code refactoring"
title: "[Refactor]: "
labels: ["enhancement"]
projects: "StellarTeams/4"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the code area to refactor and the planned changes."
    validations:
      required: true