name: "✅ Test"
description: "Add or modify tests"
title: "[Test]: "
labels: ["enhancement"]
projects: "StellarTeams/4"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the test scope and purpose, including what it will cover."
    validations:
      required: true